### ISSUE TITLE
Fix 404s for HR client docs

### ISSUE THREAD

**Issue by oraNod** [infinispan/infinispan.github.io#135]
Several links to HR client docs are 404: 

https://infinispan.org/docs/hotrod-clients/python 
https://infinispan.org/docs/hotrod-clients/ruby

https://infinispan.org/hotrod-clients/cpp/docs/8.3.2.Final/api_docs/html/index.html is linked from https://infinispan.org/hotrod-clients/cpp/docs/8.3.2.Final/index.html but does not exist

**Comment by rigazilla** [comment]
I can see https://infinispan.org/hotrod-clients/cpp/docs/8.3.1.Final/api_docs/html/index.html, but not the API for 8.3.2.Final.
Looking into the build pipeline.

**Comment by rigazilla** [comment]
CI nodes need doxygen to produce API docs

**Comment by rigazilla** [comment]
C++ API doc have been fixed: https://infinispan.org/hotrod-clients/cpp/docs/8.3.2.Final/api_docs/html/index.html

**Comment by karesti** [comment]
@rigazilla is this the latest client ?

**Comment by rigazilla** [comment]
> @rigazilla is this the latest client ?

no, there's a 9.1.0.Final, let me see if I can update the doc
