### ISSUE TITLE
FireFox displays title icon, but Chrome not

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan.github.io#146]
FireFox
![image](https://user-images.githubusercontent.com/24249373/100726327-df292b80-33d5-11eb-9e36-4af186021172.png)

Chrome
![image](https://user-images.githubusercontent.com/24249373/100726410-f9630980-33d5-11eb-8485-afc7dc65c576.png)

**Comment by karesti** [comment]
@dmvolod I use chrome and it is displayed
<img width="289" alt="Screenshot 2021-06-26 at 14 51 43" src="https://user-images.githubusercontent.com/233499/123513539-0b680a80-d68e-11eb-94cc-ab7f8f0e034b.png">

**Comment by dmvolod** [comment]
Thanks, @karesti . Now it has been fixed. Close issue.
