### ISSUE TITLE
Old site version opens for tutorials/examples instead of new one

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan.github.io#160]
Dive into tutorials/examples/any example

![image](https://user-images.githubusercontent.com/24249373/101150871-e2205800-3631-11eb-8b48-284d29687e91.png)

**Comment by dmvolod** [comment]
@karesti , @oraNod seems to be some sort of the old data need to be removed, but don't know which one

**Comment by oraNod** [comment]
@dmvolod Hi, apologies I missed this. Just added a PR to fix it here: https://github.com/infinispan/infinispan.github.io/pull/174

**Comment by dmvolod** [comment]
Thanks, @oraNod .

**Comment by dmvolod** [comment]
Problem not fixed
![image](https://user-images.githubusercontent.com/24249373/104289190-e578f000-54c9-11eb-97a3-3429aea7aa7c.png)

**Comment by oraNod** [comment]
Thanks @dmvolod It's weird. If you remove the forward slash from the URL you can access the tutorial.

![image](https://user-images.githubusercontent.com/32749632/104297148-6c25d100-54ba-11eb-8278-8b023955e6ed.png)

**Comment by dmvolod** [comment]
yes, thanks @oraNod I know this. It's for common users :smile:

**Comment by oraNod** [comment]
@dmvolod sure, I didn't mean to suggest that you didn't. TBH I'm not sure how to fix this and need to look into it some more.
