### ISSUE TITLE
infinispan-server-12.1.xsd and infinispan-config-12.1.xsd not published in schemas

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan.github.io#225]

**Comment by tristantarrant** [comment]
Added in https://github.com/infinispan/infinispan.github.io/commit/78e7cf29a7c8492700632500e7a62736a21a964c

**Comment by tristantarrant** [comment]
https://infinispan.org/schemas/infinispan-config-12.1.xsd
