### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by cmoulliard** [infinispan/infinispan.github.io#4]
When launch bin/run_dev.sh, I get this error on ubuntu :+1: 
cmoulliard@charles-ThinkPad-X230 ~/Repos/jboss/infinispan.github.io $ bin/run_dev.sh
Using profile: development
Generating site: http://localhost:4242
/usr/lib/ruby/1.9.1/psych.rb:203:in `parse': (<unknown>): could not find expected ':' while scanning a simple key at line 35 column 3 (Psych::SyntaxError)
	from /usr/lib/ruby/1.9.1/psych.rb:203:in `parse_stream'
	from /usr/lib/ruby/1.9.1/psych.rb:151:in `parse'
	from /usr/lib/ruby/1.9.1/psych.rb:127:in `load'
	from /home/cmoulliard/.bundler/ruby/1.9.1/awestruct-5523b7f299be/lib/awestruct/engine.rb:146:in `load_yaml'
	from /home/cmoulliard/.bundler/ruby/1.9.1/awestruct-5523b7f299be/lib/awestruct/engine.rb:141:in `block in load_yamls'
	from /home/cmoulliard/.bundler/ruby/1.9.1/awestruct-5523b7f299be/lib/awestruct/engine.rb:140:in `each'
	from /home/cmoulliard/.bundler/ruby/1.9.1/awestruct-5523b7f299be/lib/awestruct/engine.rb:140:in `load_yamls'
	from /home/cmoulliard/.bundler/ruby/1.9.1/awestruct-5523b7f299be/lib/awestruct/engine.rb:60:in `run'
	from /home/cmoulliard/.bundler/ruby/1.9.1/awestruct-5523b7f299be/lib/awestruct/cli/generate.rb:20:in `run'
	from /home/cmoulliard/.bundler/ruby/1.9.1/awestruct-5523b7f299be/lib/awestruct/cli/invoker.rb:102:in `invoke_generate'
	from /home/cmoulliard/.bundler/ruby/1.9.1/awestruct-5523b7f299be/lib/awestruct/cli/invoker.rb:46:in `invoke!'
	from /home/cmoulliard/.bundler/ruby/1.9.1/awestruct-5523b7f299be/bin/awestruct:9:in `<top (required)>'
	from /var/lib/gems/1.9.1/bin/awestruct:23:in `load'
	from /var/lib/gems/1.9.1/bin/awestruct:23:in `<main>'

**Comment by tristantarrant** [comment]
out of date
